-- =====================================================================
--  FIAP - Fase 4
--  Modelo de Banco de Dados para Assistente Agrícola Inteligente
--  Tabela para armazenamento de dados de sensores (Fase 2 → Fase 4)
-- =====================================================================

CREATE TABLE SENSORES_FASE4 (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UMIDADE_PCT     NUMBER(5,2)      NOT NULL,
    TEMP_C          NUMBER(5,2)      NOT NULL,
    LDR             NUMBER(10,2)     NOT NULL,
    PH_SIM          NUMBER(4,2)      NOT NULL,
    PH_OK           VARCHAR2(3)      CHECK (PH_OK IN ('SIM','NAO')),
    N_OK            NUMBER(1)        CHECK (N_OK IN (0,1)),
    P_OK            NUMBER(1)        CHECK (P_OK IN (0,1)),
    K_OK            NUMBER(1)        CHECK (K_OK IN (0,1)),
    FALTANDO        NUMBER(2),
    LIMIAR_ON       NUMBER(5,2),
    LIMIAR_OFF      NUMBER(5,2),
    RAIN_MM         NUMBER(5,2),
    POP_PCT         NUMBER(3),
    IRRIGACAO       VARCHAR2(10),
    SOURCE_FILE     VARCHAR2(100),
    DT_REGISTRO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
